environment:
  # encrypted env vars - use yarn run sls-encrypt to populate json store for stage
  GTM_CRYPT_AGENT_AWS_ACCESS_KEY_ID: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_AGENT_AWS_ACCESS_KEY_ID, env:GTM_CRYPT_AGENT_AWS_ACCESS_KEY_ID}
  GTM_CRYPT_AGENT_AWS_SECRET_ACCESS_KEY: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_AGENT_AWS_SECRET_ACCESS_KEY, env:GTM_CRYPT_AGENT_AWS_SECRET_ACCESS_KEY}
  GTM_CRYPT_GITHUB_WEBHOOK_SECRET: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_GITHUB_WEBHOOK_SECRET, env:GTM_CRYPT_GITHUB_WEBHOOK_SECRET}
  GTM_CRYPT_GITHUB_TOKEN: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_GITHUB_TOKEN, env:GTM_CRYPT_GITHUB_TOKEN}
  GTM_CRYPT_JENKINS_TOKEN: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_JENKINS_TOKEN, env:GTM_CRYPT_JENKINS_TOKEN}
  GTM_CRYPT_LAUNCHDARKLY_API_TOKEN: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_LAUNCHDARKLY_API_TOKEN, env:GTM_CRYPT_LAUNCHDARKLY_API_TOKEN}
  GTM_CRYPT_SONAR_GITHUB_OAUTH: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_SONAR_GITHUB_OAUTH, env:GTM_CRYPT_SONAR_GITHUB_OAUTH}
  GTM_CRYPT_SONAR_LOGIN: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_SONAR_LOGIN, env:GTM_CRYPT_SONAR_LOGIN}
  GTM_CRYPT_TEAMCITY_PASSCODE: ${self:custom.kmsSecrets.secrets.GTM_CRYPT_TEAMCITY_PASSCODE, env:GTM_CRYPT_TEAMCITY_PASSCODE}
  # unencrypted env vars - add values to .env
  GTM_AWS_REGION: ${env:GTM_AWS_REGION, 'ap-southeast-2'}
  GTM_SQS_PENDING_QUEUE: ${env:GTM_SQS_PENDING_QUEUE, 'gtmPendingQueue'}
  GTM_SQS_RESULTS_QUEUE: ${env:GTM_SQS_RESULTS_QUEUE, 'gtmResultsQueue'}
  GTM_SNS_RESULTS_TOPIC: ${env:GTM_SNS_RESULTS_TOPIC, 'gtmResultsSNSTopic'}
  GTM_GITHUB_HOST:  ${env:GTM_GITHUB_HOST, 'api.github.com'}
  GTM_GITHUB_DEBUG: ${env:GTM_GITHUB_DEBUG, 'true'}
  GTM_GITHUB_TIMEOUT: ${env:GTM_GITHUB_TIMEOUT, '5000'}
  GTM_GITHUB_PATH_PREFIX: ${env:GTM_GITHUB_PATH_PREFIX}
  GTM_GITHUB_PROXY: ${env:GTM_GITHUB_PROXY}
  GTM_TASK_CONFIG_FILENAME: ${env:GTM_TASK_CONFIG_FILENAME, '.githubTaskManager.json'}
  GTM_AGENT_PORT: ${env:GTM_AGENT_PORT, '9091'}
  GTM_JENKINS_USER: ${env:GTM_JENKINS_USER}
  GTM_JENKINS_URL: ${env:GTM_JENKINS_URL}
  GTM_JENKINS_CSRF: ${env:GTM_JENKINS_CSRF}
  GTM_TEAMCITY_USER: ${env:GTM_TEAMCITY_USER}
  GTM_TEAMCITY_URL: ${env:GTM_TEAMCITY_URL}
  GTM_DOCKER_IMAGE_WHITELIST: ${env:GTM_DOCKER_IMAGE_WHITELIST, 'alpine:*,zotoio/*'}
  GTM_DOCKER_IMAGE_WHITELIST_FILE: ${env:GTM_DOCKER_IMAGE_WHITELIST_FILE, '.dockerImageWhitelistExample'}
  GTM_DOCKER_COMMANDS_ALLOWED: ${env:GTM_DOCKER_COMMANDS_ALLOWED, 'true'}
  GTM_DOCKER_ALLOW_PULL: ${env:GTM_DOCKER_ALLOW_PULL, 'true'}
  GTM_DOCKER_DEFAULT_WORKER_IMAGE: ${env:GTM_DOCKER_DEFAULT_WORKER_IMAGE, 'zotoio/gtm-worker:latest'}
  IAM_ENABLED: ${env:IAM_ENABLED}
  GTM_LOGSTASH_HOST: ${env:GTM_LOGSTASH_HOST}
  GTM_LOGSTASH_PORT: ${env:GTM_LOGSTASH_PORT}
  GTM_SONAR_HOST_URL: ${env:GTM_SONAR_HOST_URL}
  GTM_SONAR_GITHUB_ENDPOINT: ${env:GTM_SONAR_GITHUB_ENDPOINT}
  GTM_SONAR_PROJECTNAME_PREFIX: ${env:GTM_SONAR_PROJECTNAME_PREFIX, 'github::'}
  GTM_SONAR_ANALYSIS_MODE: ${env:GTM_SONAR_ANALYSIS_MODE, 'preview'}
  GTM_SONAR_SOURCES: ${env:GTM_SONAR_SOURCES, 'src'}
  GTM_SONAR_JAVA_BINARIES: ${env:GTM_SONAR_JAVA_BINARIES, 'target'}
  GTM_SONAR_MODULES: ${env:GTM_SONAR_MODULES}
  GTM_TASK_CONFIG_DEFAULT_URL: ${env:GTM_TASK_CONFIG_DEFAULT_URL}
  GTM_TASK_CONFIG_DEFAULT_MESSAGE_PATH: ${env:GTM_TASK_CONFIG_DEFAULT_MESSAGE_PATH}
  GTM_DYNAMO_TABLE_EVENTS: ${env:GTM_DYNAMO_TABLE_EVENTS, 'GtmEvents'}
  GTM_DYNAMO_TABLE_AGENTS: ${env:GTM_DYNAMO_TABLE_AGENTS, 'GtmAgents'}
  GTM_AWS_VPC_ID: ${env:GTM_AWS_VPC_ID}
  GTM_BASE_URL: ${env:GTM_BASE_URL, 'http://localhost:9091'}
  GTM_S3_DEPENDENCY_BUCKET: ${env:GTM_S3_DEPENDENCY_BUCKET, 'gtmstorage'}
  GTM_WELCOME_MESSAGE_ENABLED: ${env:GTM_WELCOME_MESSAGE_ENABLED, 'true'}
  GTM_REPO_BLACKLIST: ${env:GTM_REPO_BLACKLIST, '.*ignore-repo.*,.*another-repo.*'}
  GTM_AWS_KMS_KEY_ID: ${env:GTM_AWS_KMS_KEY_ID}